[toolchain]
channel = "1.83.0"
components = [
    "rustc",
    "rust-src",
    "cargo",
    "rustfmt",
    "rust-std",
    "rust-analyzer",
    "llvm-tools"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]
profile = "default"
